### PR TITLE
support Android v2 embedding

### PR DESCRIPTION
**Pull request by Vov4yk**

### CODE REVIEW

**Comment by danielnordh** [comment]
This seems to include buildship additions and firebase.core additions.
Is that required?

**Comment by zionnite** [comment]
@Vov4yk , can you poease instruction how to make use of your updates?

**Comment by Vov4yk** [comment]
@zionnite I'm not sure I understood what instruction I can provide.
I'm using this library in my project. But met a problem when update Flutter SDK that I couln't use this library coz it's not supporting V2 for android. I've made a changes that allow me to use the library and have shared my solution. Maybe it could be useful for some one else who faced the same problem. Is it your case?

**Comment by zionnite** [comment]
Thank you very much Sir for your quick response, 

Am having extalty the same  issue with you, but I don't how to add your solution to my code😩😫

Please how do I go about that?, have only added this package to my flutter app

**Comment by Vov4yk** [comment]
Sure. I've done fork into my repo. 
I'm using direct url in my .yaml file. 
But should warn you that there is no guaranty with my fork and how long it would exist. Use own fork should be more stable solution.
`plain_notification_token:
    git:
      url: git@github.com:byga-net/plain_notification_token.git`

**Comment by zionnite** [comment]
Thanks Sir,
You are a life saver

**Comment by zionnite** [comment]
good morning sir,

attempting to use the solution you provided I encounter this, of course, I forked it

```
  plain_notification_token:
    git:
      url: git@github.com:zionnite/plain_notification_token.git
```

Screen Shot 2022-02-04 at 9 02 00 AM

**Comment by zionnite** [comment]
> good morning sir,
> 
> attempting to use the solution you provided I encounter this, of course, I forked it
> 
> ```
>   plain_notification_token:
>     git:
>       url: git@github.com:zionnite/plain_notification_token.git
> ```
> 
> Screen Shot 2022-02-04 at 9 02 00 AM
> 
> _**same error encounter when i use the below code too**_
> 
> ```
>   plain_notification_token:
>     git:
>       url: git@github.com:byga-net/plain_notification_token.git
> ```

Hello @Vov4yk 

I was able to resolve this error and I change the code to this 

```
  plain_notification_token:
    git:
      url: https://github.com/zionnite/plain_notification_token.git
```

I was able to run the `pubspec.yaml` file but I encounter another issue while running the flutter app for android

below is the screenshot
Screen Shot 2022-02-04 at 9 48 18 AM

**Comment by Vov4yk** [comment]
@zionnite 
Maybe that discussion could help you to find proper solution.
https://stackoverflow.com/questions/53484122/how-do-you-force-pub-get-to-get-latest-from-git

**Comment by zionnite** [comment]
> @zionnite Maybe that discussion could help you to find proper solution. https://stackoverflow.com/questions/53484122/how-do-you-force-pub-get-to-get-latest-from-git


error still persist, could not run the app on android, working well on ios

**Comment by zionnite** [comment]
the issue thats persisting now is this

 ```
local variable result is accessed from within inner class; needs to be declared final
                                    result.success(task.getResult().getToken());
```
please see the above comment screenshot

**Comment by Vov4yk** [comment]
On latest screenshoot the app want use library from cache by kikuchy, so it has no V2 fix. Your try with https access instead ssh wasn't success. Try to add ssh key on your machine (or CI). Than you should be able to use your git@github.com:zionnite/plain_notification_token.git

**Comment by zionnite** [comment]
Hello sir, 
have really learned something like adding ssh to my machine, (thanks)

```

  plain_notification_token:
    git:
      url: git@github.com:zionnite/plain_notification_token.git
```

But this time when i run the build for android, these errors still persist


```
/Users/apple/.pub-cache/git/plain_notification_token-3709a43167c63bd8f22570afe4fb21fe2e982c39/android/src/main/java/net/kikuchy/plain_notification_token/PlainNotificationTokenPlugin.java:81: error: local variable result is accessed from within inner class; needs to be declared final
                                    result.success(task.getResult().getToken());
                                    ^
Note: /Users/apple/.pub-cache/git/plain_notification_token-3709a43167c63bd8f22570afe4fb21fe2e982c39/android/src/main/java/net/kikuchy/plain_notification_token/PlainNotificationTokenPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':plain_notification_token:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 58s
Exception: Gradle task assembleDebug failed with exit code 1
```


can you please take a look at this repo, if I actually forked the right repo?

**git@github.com:**`zionnite/plain_notification_token.git`

**Comment by zionnite** [comment]
Screen Shot 2022-02-04 at 2 15 23 PM

**Comment by Vov4yk** [comment]
It looks like the app still using cached kikuchy library instead new fork. Please, check if you are using force pub's update.
`apple/.pub-cache/git/plain_notification_token-3709a43167c63bd8f22570afe4fb21fe2e982c39/android/src/main/java/net/kikuchy/plain_notification_token/PlainNotificationTokenPlugin.java`

**Comment by zionnite** [comment]
> It looks like the app still using cached kikuchy library instead new fork. Please, check if you are using force pub's update. `apple/.pub-cache/git/plain_notification_token-3709a43167c63bd8f22570afe4fb21fe2e982c39/android/src/main/java/net/kikuchy/plain_notification_token/PlainNotificationTokenPlugin.java`

issue still persist sir

**Comment by zionnite** [comment]
i deleted the `.pub-cache/` yet issue still persist

**Comment by zionnite** [comment]
Sir, can you please help check your repo

**Comment by zionnite** [comment]
@Vov4yk **`VICTORY`** at last

the issue was called from this line

```
    @Override
    public void onMethodCall(**@NonNull MethodCall call, @NonNull Result result**) {
```

**Solution**

```
    @Override
    public void onMethodCall(**@NonNull final MethodCall call, @NonNull final Result result**) {
```


> Now my code is running

thank you for your time @Vov4yk !

**Pull request merged**
